image: rhiananthony/dsde-toolbox:gitlab-runner-11.4.4

stages:
  - dev
  - test
  - staging
  - prod

deploy_dev:
  tags:
    - green
  stage: dev
  script:
    - export LIRA_ENVIRONMENT=dev
    - bash deploy/gitlab/deploy_lira.sh

deploy_test:
  tags:
    - green
  stage: test
  script:
    - export LIRA_ENVIRONMENT=test
    - bash deploy/gitlab/deploy_lira.sh
  when: manual

deploy_staging:
  tags:
    - green
  stage: staging
  script:
    - export LIRA_ENVIRONMENT=staging
    - bash deploy/gitlab/deploy_lira.sh
  when: manual

deploy_lira:
  tags:
    - green
  stage: prod
  script:
    - export LIRA_ENVIRONMENT=prod
    - bash deploy/gitlab/deploy_lira.sh
  when: manual
