image: rhiananthony/dsde-toolbox:gitlab-runner-11.4.4

stages:
  - staging

deploy_lira:
  tags:
    - green
  stage: staging
  script:
    - export LIRA_ENVIRONMENT=dev
    - bash deploy/gitlab/deploy_lira.sh
