dev:
  script:
    - ENVIRONMENT=dev
    - bash kubernetes/deploy_lira.sh

test:
  script:
    - ENVIRONMENT=test
    - bash kubernetes/test_deploy_config.sh

staging:
  script:
    - ENVIRONMENT=staging
    - bash kubernetes/test_deploy_config.sh

prod:
  script:
    - ENVIRONMENT=prod
    - bash kubernetes/test_deploy_config.sh
    