image: rhiananthony/dsde-toolbox:gitlab-runner-11.4.4

stages:
  - deployment

deploy_lira:
  tags:
    - green
  stage: deployment
  script:
    - export LIRA_ENVIRONMENT=staging
    - bash deploy/gitlab/deploy_lira.sh
