image: rhiananthony/dsde-toolbox:gitlab-runner-11.4.4

stages:
  - dev

deploy_lira:
  tags:
    - green
  stage: dev
  script:
    - export LIRA_ENVIRONMENT=dev
    - bash deploy/config_files/gitlab/deploy_lira.sh
