swagger: '2.0'
info:
  title: HCA DCP Green Box API
  description: Human Cell Atlas Data Coordination Platform Secondary Analysis ("Green Box") API
  version: '0.1.0'
host: localhost:8080
schemes:
  - https
produces:
  - application/json
tags:
- name: Listener
  externalDocs:
    description: Find out more about the Lira service
    url: 'https://github.com/HumanCellAtlas/lira/wiki'
- name: Information
  description: Information about the Lira service
paths:
  /version:
    get:
      tags:
      - Information
      summary: Return the version of this Lira and its dependencies.
      operationId: 'lira.api.version.get_version'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/VersionResponse'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error
          schema:
            type: string
  /health:
    get:
      tags:
      - Information
      summary: health check
      operationId: 'lira.api.health.get'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/HealthCheckResponse'
        default:
          description: Error
          schema:
            type: string
  /notifications:
    post:
      tags:
      - Listener
      summary: Send notifications
      description: |
        Notify green about bundles to process
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: false
          schema:
            $ref: '#/definitions/Notification'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/NotificationResponse'
        401:
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Not Found
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Error
          schema:
            type: string
definitions:
  Notification:
    type: object
    properties:
      match:
        $ref: '#/definitions/Match'
  Match:
    type: object
    properties:
      bundle_uuid:
        type: string
      bundle_version:
        type: string
  Error:
    type: object
    properties:
      error:
        type: string
  NotificationResponse:
    type: object
    properties:
      status:
        type: string
      id:
        type: string
  HealthCheckResponse:
    type: object
    properties:
      status:
        type: string
  VersionResponse:
    type: object
    properties:
      launch_time:
        type: string
      lira_version:
        type: string
      cromwell_tools_version:
        type: string
      submit_wdl_version:
        type: string
      run_mode:
        type: string
      workflow_info:
        type: object
